// Sync the Kineto MCP server package with the repository contracts:
//
//   kineto.features.json          → packages/kineto-mcp/contracts/features.json
//   kineto.integrations.json      → packages/kineto-mcp/contracts/integrations.json
//   kineto.module-metadata.json   → packages/kineto-mcp/contracts/module-metadata.json
//   ai/kineto.rules.md (rendered) → packages/kineto-mcp/contracts/rules.md
//   scripts/integrations/lib.mjs  → packages/kineto-mcp/src/lib.mjs
//   (+ contracts/meta.json with the versions everything was generated from)
//
// The package is published on its own (`npx @dong-gri/kineto-mcp`), so it
// cannot reach into this repository at runtime; instead it carries a verified
// copy of the contracts. This script is the only writer of those copies and
// `--check` fails when they drift, so the MCP server can never answer from a
// stale feature contract.
//
//   node scripts/build-mcp.mjs           # write
//   node scripts/build-mcp.mjs --check   # fail if the package is stale
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadContracts, renderAll, writeFiles } from './generate-integrations.mjs';
import { dash } from './integrations/lib.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const MCP_PACKAGE_DIR = 'packages/kineto-mcp';

const GENERATED = (source) => `// GENERATED by scripts/build-mcp.mjs from ${source} — edit the source, then run \`npm run integrations:build\`.\n`;

/** Render every generated file of the MCP package as { path: content }. */
export function renderMcpPackage(contracts = loadContracts()) {
  const { features, integrations, pkg } = contracts;
  const metadata = JSON.parse(fs.readFileSync(path.join(root, 'kineto.module-metadata.json'), 'utf8'));
  const rules = renderAll(contracts)['ai/kineto.rules.md'];
  const lib = fs.readFileSync(path.join(root, 'scripts/integrations/lib.mjs'), 'utf8');
  const json = (value) => JSON.stringify(value, null, 2) + '\n';
  // Per-module guides are named either camelCase or dashed; map each module
  // to the one that exists so the server can link it without guessing.
  const guides = new Set(fs.readdirSync(path.join(root, 'docs/modules')));
  const moduleDocs = {};
  for (const module of features.modules) {
    const candidate = [`${module.name}.md`, `${dash(module.name)}.md`].find((file) => guides.has(file));
    if (candidate) moduleDocs[module.name] = `docs/modules/${candidate}`;
  }
  return {
    [`${MCP_PACKAGE_DIR}/contracts/features.json`]: json(features),
    [`${MCP_PACKAGE_DIR}/contracts/integrations.json`]: json(integrations),
    [`${MCP_PACKAGE_DIR}/contracts/module-metadata.json`]: json(metadata),
    [`${MCP_PACKAGE_DIR}/contracts/rules.md`]: rules,
    [`${MCP_PACKAGE_DIR}/contracts/meta.json`]: json({
      generatedBy: 'scripts/build-mcp.mjs',
      kinetoVersion: pkg.version,
      featureContractVersion: features.contractVersion,
      integrationsVersion: integrations.integrationsVersion,
      moduleCount: features.moduleCount,
      intentCount: integrations.intents.length,
      ecosystems: Object.keys(integrations.ecosystems),
      repository: 'https://github.com/catgarret/kineto',
      site: 'https://kineto.dongri.me',
      moduleDocs
    }),
    [`${MCP_PACKAGE_DIR}/src/lib.mjs`]: GENERATED('scripts/integrations/lib.mjs') + lib
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  const files = renderMcpPackage();
  const stale = writeFiles(files, { check });
  if (check) {
    if (stale.length) { console.error(`build-mcp --check FAILED — stale:\n  - ${stale.join('\n  - ')}`); process.exit(1); }
    console.log(`build-mcp --check OK — ${Object.keys(files).length} generated files in ${MCP_PACKAGE_DIR} are current.`);
  } else {
    console.log(`Synced ${Object.keys(files).length} contract files into ${MCP_PACKAGE_DIR}.`);
  }
}
