// What does registering ONE module cost on top of `@dong-gri/kineto/core`?
//
// The modular build (dist/modular) is plain ESM: an entry file plus shared
// chunks it imports. This script follows each entry's static imports and
// reports the bytes a consumer adds for a module beyond what `core` already
// pulls in — raw and gzip — so the cost of the modular path is visible before
// anyone installs anything. No bundler runs here: the numbers are the files a
// browser (native ESM via a CDN) downloads, which is also an upper bound on
// what a bundler emits for `core + that module`.
//
//   node scripts/module-cost.mjs          print the table
//   node scripts/module-cost.mjs --write  refresh docs/module-cost.md
//
// Refreshed by `npm run release:prepare` so each release records its own
// numbers. It is intentionally NOT part of `npm run build` or a CI freshness
// check: gzip output can differ by a few bytes between Node/zlib versions, and
// a cost table should not turn a patch on one runner red.
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const modularDir = path.join(root, 'dist', 'modular');
const outFile = path.join(root, 'docs', 'module-cost.md');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const contract = JSON.parse(fs.readFileSync(path.join(root, 'kineto.features.json'), 'utf8'));

// Static `import … from "./x.js"` / `export … from "./x.js"` / bare `import "./x.js"`.
// Dynamic import() is excluded on purpose: those chunks load only when used.
const STATIC_IMPORT = /(?:^|[;\s}])(?:import|export)\s*(?:[^'"()]*?from\s*)?["'](\.{1,2}\/[^"']+)["']/g;

const sizeCache = new Map();
function fileSize(file) {
  if (!sizeCache.has(file)) {
    const bytes = fs.readFileSync(file);
    sizeCache.set(file, { raw: bytes.length, gzip: zlib.gzipSync(bytes, { level: 9 }).length });
  }
  return sizeCache.get(file);
}

// Every file reachable from `entry` through static relative imports.
function closure(entry) {
  const seen = new Set();
  const stack = [entry];
  while (stack.length) {
    const file = stack.pop();
    if (seen.has(file)) continue;
    seen.add(file);
    const source = fs.readFileSync(file, 'utf8');
    for (const [, specifier] of source.matchAll(STATIC_IMPORT)) {
      stack.push(path.resolve(path.dirname(file), specifier));
    }
  }
  return seen;
}

const sum = (files) => [...files].reduce((total, file) => {
  const size = fileSize(file);
  return { raw: total.raw + size.raw, gzip: total.gzip + size.gzip };
}, { raw: 0, gzip: 0 });

const kb = (bytes) => (bytes / 1024).toFixed(1);

export function measureModuleCosts() {
  const coreFiles = closure(path.join(modularDir, 'core.js'));
  const core = sum(coreFiles);
  const rows = contract.modules.map((module) => module.name).sort().map((name) => {
    const entry = path.join(modularDir, 'modules', `${name}.js`);
    if (!fs.existsSync(entry)) throw new Error(`dist/modular/modules/${name}.js is missing — run npm run build`);
    const extra = [...closure(entry)].filter((file) => !coreFiles.has(file));
    return { name, files: extra.length, ...sum(extra) };
  });
  return { core, rows };
}

function markdown({ core, rows }) {
  const byCost = [...rows].sort((a, b) => b.gzip - a.gzip);
  const lines = [
    '# Module cost on top of `core`',
    '',
    `> Generated by \`node scripts/module-cost.mjs --write\` for v${pkg.version} (refreshed by \`npm run release:prepare\`).`,
    '> Do not edit by hand.',
    '',
    'Bytes one module adds to `import Kineto from \'@dong-gri/kineto/core\'` in the modular build',
    '(`dist/modular`): the module entry plus shared chunks that `core` does not already load, gzip level 9',
    'per file. Chunks shared between modules are counted for each module that needs them, so the cost of',
    'two modules together is at most the sum of their rows. A bundler usually lands a little lower',
    '(one output file compresses better than several); whole-app numbers are in',
    '[consumer-bundle-size.md](consumer-bundle-size.md).',
    '',
    `**\`core\` itself:** ${kb(core.raw)} KB raw · **${kb(core.gzip)} KB gzip**. The CSS (\`style.css\`) is one file for every entry.`,
    '',
    '| Module | Extra files | Raw | Gzip |',
    '| --- | ---: | ---: | ---: |',
    ...byCost.map((row) => `| \`${row.name}\` | ${row.files} | ${kb(row.raw)} KB | ${kb(row.gzip)} KB |`),
    ''
  ];
  return lines.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = measureModuleCosts();
  const output = markdown(result);
  if (process.argv.includes('--write')) {
    fs.writeFileSync(outFile, output);
    console.log(`Wrote ${path.relative(root, outFile)} — ${result.rows.length} modules, core ${kb(result.core.gzip)} KB gzip.`);
  } else {
    console.log(output);
  }
}
