// GENERATED by scripts/sync-playground-options.mjs from kineto.features.json — do not edit.
//
// activation name → modules that have an OPTION of that name. `data-kt-<name>` on an
// element of one of those modules is that module's option, not a second module.
// Composition stays available by nesting elements or by calling Kineto.create().
export const ACTIVATION_OPTION_OWNERS = Object.freeze({
  "cursor": [
    "lightbox"
  ],
  "drag": [
    "fullpage",
    "radial",
    "slider"
  ],
  "hold": [
    "brushReveal",
    "textReveal",
    "textSplit",
    "textTransition"
  ],
  "progress": [
    "loader",
    "loadingIndicator",
    "slider"
  ]
});
